name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Consider specifying a more specific version if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build==0.8.0 twine==4.0.0  # Specify versions used in your local setup

    - name: Build package
      run: |
        python -m build
        echo "Build completed"

    - name: Check package with Twine
      run: |
        twine check dist/*
        echo "Twine check completed"

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true  # Enable verbose output to diagnose issues during publishing

